/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.11/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application

    // Code quality plugins
    checkstyle
    id("com.github.spotbugs") version "6.0.26"
    id("com.diffplug.spotless") version "7.0.0.BETA4"
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // SpotBugs annotations
    compileOnly("com.github.spotbugs:spotbugs-annotations:4.8.6")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "studentdb.shell.Shell"
}

tasks.named<JavaExec>("run") {
    standardInput = System.`in`
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

// Checkstyle configuration
checkstyle {
    toolVersion = "12.1.1"
    configFile = file("${rootProject.projectDir}/config/checkstyle/checkstyle.xml")
}

// SpotBugs configuration
spotbugs {
    ignoreFailures = false
    showStackTraces = true
    showProgress = true
    effort = com.github.spotbugs.snom.Effort.MAX
    reportLevel = com.github.spotbugs.snom.Confidence.LOW
    excludeFilter = file("${rootProject.projectDir}/config/spotbugs/excludeFilter.xml")
}

tasks.withType<com.github.spotbugs.snom.SpotBugsTask>().configureEach {
    reports.create("html") {
        required = true
        outputLocation = file("${project.layout.buildDirectory.get()}/reports/spotbugs/${name}.html")
    }
}

// Spotless configuration
spotless {
    java {
        target("src/**/*.java")
        googleJavaFormat("1.24.0")
    }
}
